### ISSUE TITLE
How to set 'clip.num_frames

### ISSUE THREAD

**Issue by feaonal** [HolyWu/vs-rife#12]
How to set the frames numbers?I only found the "multi: int ="in "__init__.py".Can I set the whole number of the frames numbers?Like 60 fps?Thanks!

**Comment by HolyWu** [comment]
No. You can only set the multiple of the original frame number to interpolate, like 2x, 3x, or 4x, etc.

**Comment by feaonal** [comment]
> No. You can only set the multiple of the original frame number to interpolate, like 2x, 3x, or 4x, etc.

OK,thanks.
