### ISSUE TITLE
error when run cmd "python -m vsrife"

### ISSUE THREAD

**Issue by Usulyre** [HolyWu/vs-rife#24]
Got this error when run cmd "python -m vsrife"

C:\Windows\System32>python -m vsrife
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Program Files\Python311\Lib\site-packages\vsrife\__init__.py", line 13, in <module>
    from torch_tensorrt.fx import compile
  File "C:\Program Files\Python311\Lib\site-packages\torch_tensorrt\fx\__init__.py", line 1, in <module>
    from .converters import *  # noqa: F403 F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\torch_tensorrt\fx\converters\__init__.py", line 2, in <module>
    import tensorrt as trt
ModuleNotFoundError: No module named 'tensorrt'

C:\Windows\System32>

Also, where do I put the files i downloaded from after i uncompress them:

https://github.com/HolyWu/vs-rife/releases/download/v3.1.0/CUDA-11.7_cuDNN-8.6.0_TensorRT-8.5.2.2_win64.7z

**Comment by aodgizmo** [comment]
https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html
will tell you how to install the TensorRT. 

Pretty much download the zip, 
extract it, 
set system environment PATH to the folder you just extracted or CUDA{version}/Bin if missing,
move DLL files from LIB to CUDA/{Version}/Bin, 
and run a couple PIP installs. Goto Extracted folder/python and run 
python.exe -m pip install tensorrt-*-cp3x-none-win_amd64.whl

After all that you need to run a couple PIP installs, these can be found in the extracted folder of TensorRT you just downloaded from nvidia.
python3 -m pip install <installpath>\graphsurgeon\graphsurgeon-0.4.6-py2.py3-none-any.whl
python3 -m pip install <installpath>\uff\uff-0.6.9-py2.py3-none-any.whl
python3 -m pip install <installpath>\onnx_graphsurgeon\onnx_graphsurgeon-0.3.12-py2.py3-none-any.whl

Good luck!

**Comment by Usulyre** [comment]
> https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html will tell you how to install the TensorRT.
> 
> Pretty much download the zip, extract it, set system environment PATH to the folder you just extracted or CUDA{version}/Bin if missing, move DLL files from LIB to CUDA/{Version}/Bin, and run a couple PIP installs. Goto Extracted folder/python and run python.exe -m pip install tensorrt-*-cp3x-none-win_amd64.whl
> 
> After all that you need to run a couple PIP installs, these can be found in the extracted folder of TensorRT you just downloaded from nvidia. python3 -m pip install \graphsurgeon\graphsurgeon-0.4.6-py2.py3-none-any.whl python3 -m pip install \uff\uff-0.6.9-py2.py3-none-any.whl python3 -m pip install \onnx_graphsurgeon\onnx_graphsurgeon-0.3.12-py2.py3-none-any.whl
> 
> Good luck!

Hi and thanks for your reply.

I got an error message when I ran that first cmdline. I have a GTX 1660.

ERROR: tensorrt-8.5.2.2-cp310-none-win_amd64.whl is not a supported wheel on this platform.

**Comment by aodgizmo** [comment]
> Hi and thanks for your reply.
> 
> I got an error message when I ran that first cmdline. I have a GTX 1660.
> 
> ERROR: tensorrt-8.5.2.2-cp310-none-win_amd64.whl is not a supported wheel on this platform.

Make sure you are using python 3.10 if you are typing 310. Also try updating PIP to newest version and make sure you have python 64 bit version.

More info on your possible problem. https://stackoverflow.com/a/39945920

**Comment by Usulyre** [comment]
> > Hi and thanks for your reply.
> > I got an error message when I ran that first cmdline. I have a GTX 1660.
> > ERROR: tensorrt-8.5.2.2-cp310-none-win_amd64.whl is not a supported wheel on this platform.
> 
> Make sure you are using python 3.10 if you are typing 310. Also try updating PIP to newest version and make sure you have python 64 bit version.
> 
> More info on your possible problem. https://stackoverflow.com/a/39945920

I have python 64 bit 3.11 

 Does that matter?

**Comment by aodgizmo** [comment]
If you have 3.11, you need to type 3.11 when typing the command

tensorrt-8.5.2.2-cp310-none-win_amd64.whl
should be
tensorrt-8.5.2.2-cp311-none-win_amd64.whl

**Comment by Usulyre** [comment]
> If you have 3.11, you need to type 3.11 when typing the command
> 
> tensorrt-8.5.2.2-cp310-none-win_amd64.whl should be tensorrt-8.5.2.2-cp311-none-win_amd64.whl

\Program Files\Python310\lib\site-packages\torch_tensorrt\fx\tracer\acc_tracer\acc_ops.py:840: UserWarning: Unable to import torchvision related libraries.: No module named 'torchvision'. Please install torchvision lib in order to lower stochastic_depth

**Comment by aodgizmo** [comment]
What does it say when you type nvcc --version. Should say if you have CUDA installed or not.

For Please install torchvision lib in order to lower stochastic_depth

Try pip install torchvision

Not trying to be mean, but if you can't figure out these simple problems your gonna have a bad time trying to run the more complicated tasks. Kinda seems like you don't even have CUDA install from nvidia even.

**Comment by Usulyre** [comment]
> What does it say when you type nvcc --version. Should say if you have CUDA installed or not.
> 
> For Please install torchvision lib in order to lower stochastic_depth
> 
> Try pip install torchvision
> 
> Not trying to be mean, but if you can't figure out these simple problems your gonna have a bad time trying to run the more complicated tasks. Kinda seems like you don't even have CUDA install from nvidia even.

nvcc-version doesn't work as is?

I tried to follow this guide:

https://www.svp-team.com/forum/viewtopic.php?pid=81456#p81456

I still had the same issue with "RIFE: cuda is not available"

**Comment by aodgizmo** [comment]
You need to download and install Nvidia Cuda toolkit. You might need to make a account with them first.

https://developer.nvidia.com/cuda-downloads

When installed you should be able to run and see this output.

>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

Find a guide to install CUDA and make sure to add them to your system PATH or it wont find it when you try to run them. Also if you get stuck , try asking CHAT-GPT about how to install it. Good Luck!

**Comment by Usulyre** [comment]
I thought everything is included for the windows release:

 "For ease of installation on Windows, you can download the 7z file on [Releases](https://github.com/HolyWu/vs-rife/releases) which contains required runtime libraries and Python wheel file"

**Comment by aodgizmo** [comment]
> I thought everything is included for the windows release:
> 
> "For ease of installation on Windows, you can download the 7z file on [Releases](https://github.com/HolyWu/vs-rife/releases) which contains required runtime libraries and Python wheel file"

NVIDIA CUDA is a separate thing and needs to be installed for many AI programs to work.

**Comment by Usulyre** [comment]
> > I thought everything is included for the windows release:
> > "For ease of installation on Windows, you can download the 7z file on [Releases](https://github.com/HolyWu/vs-rife/releases) which contains required runtime libraries and Python wheel file"
> 
> NVIDIA CUDA is a separate thing and needs to be installed for many AI programs to work.

Would cuda for python work?

pip install cuda-python

**Comment by aodgizmo** [comment]
> Would cuda for python work?
> 
> pip install cuda-python

Not sure, I installed mine with the package from NVIDIA website.

**Comment by Usulyre** [comment]
> > Would cuda for python work?
> > pip install cuda-python
> 
> Not sure, I installed mine with the package from NVIDIA website.

Downloaded cudatoolkit v11.7

Not sure what from the custom install selection that I need keep check for cuda to be available for vs-rife.

I just selected cuda runtime libraries and nvcc.

Still not working.

**Comment by aodgizmo** [comment]
When you run nvcc --version

Do you see?

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

If it says something like command not found, it is most likely not set in the path correctly.

https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#post-installation-actions

**Comment by Usulyre** [comment]
> When you run nvcc --version
> 
> Do you see?
> 
> nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2022 NVIDIA Corporation Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022 Cuda compilation tools, release 11.8, V11.8.89 Build cuda_11.8.r11.8/compiler.31833905_0
> 
> If it says something like command not found, it is most likely not set in the path correctly.
> 
> https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#post-installation-actions

I have to go to the actual folder where nvcc is to run that command

**Comment by aodgizmo** [comment]
Ya, that means you did not add it to the PATH correctly. When it is added to the path it tells the system where to find NVCC when you run it.

**Comment by Usulyre** [comment]
I'm using windows 11, can it be set through environment variiables

**Comment by aodgizmo** [comment]
https://medium.com/analytics-vidhya/tensorflow-gpu-how-to-install-tensorflow-with-nvidia-cuda-cudnn-and-gpu-support-on-windows-6158cffc1c29

step 5.3: Confirming that CUDA environment variables are set in Windows

For CUDA to function properly, you will need to ensure that CUDA environment variables are set in your PC‘s Path. To confirm, you will need to check the Environment Variables. This can be found by following these steps

Control Panel -> System and Security -> System-> Advanced System settings.

This will open up a window, click on the Advanced tab. as shown below
Image by author

https://miro.medium.com/v2/resize:fit:640/format:webp/1*a9zoQnDYS4vF8rofF7levw.png

https://miro.medium.com/v2/resize:fit:640/format:webp/1*7WOGbl9LAE4hoSjV-9Wehg.png

    These paths are automatically added, but in case you can’t find them. Just type in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin and C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\V11.2\libnvvp.

**Comment by Usulyre** [comment]
I'm using windows 11, can it be set through environment variiables

> Ya, that means you did not add it to the PATH correctly. When it is added to the path it tells the system where to find NVCC when you run it.

I'm using windows 11, can it be set through environment variiables?

**Comment by Usulyre** [comment]
> https://medium.com/analytics-vidhya/tensorflow-gpu-how-to-install-tensorflow-with-nvidia-cuda-cudnn-and-gpu-support-on-windows-6158cffc1c29
> 
> step 5.3: Confirming that CUDA environment variables are set in Windows
> 
> For CUDA to function properly, you will need to ensure that CUDA environment variables are set in your PC‘s Path. To confirm, you will need to check the Environment Variables. This can be found by following these steps
> 
> Control Panel -> System and Security -> System-> Advanced System settings.
> 
> This will open up a window, click on the Advanced tab. as shown below Image by author
> 
> https://miro.medium.com/v2/resize:fit:640/format:webp/1*a9zoQnDYS4vF8rofF7levw.png
> 
> https://miro.medium.com/v2/resize:fit:640/format:webp/1*7WOGbl9LAE4hoSjV-9Wehg.png
> 
> ```
> These paths are automatically added, but in case you can’t find them. Just type in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin and C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\V11.2\libnvvp.
> ```

I dont know what libnvvp is for which i do not currently have.

nvcc works now but still getting the error of cuda not available.

**Comment by aodgizmo** [comment]
Since I have 11.8 CUDA installed, mine is located at...

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp

You can try adding these to the PATH if you installed them to the same location.
Also you can check them folders to see if that is where they are.

**Comment by Usulyre** [comment]
> Since I have 11.8 CUDA installed, mine is located at...
> 
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp
> 
> You can try adding these to the PATH if you installed them to the same location. Also you can check them folders to see if that is where they are.

By the way, this is part of the error when one looks at init.py of vsrife

if not torch.cuda.is_available():
raise vs.Error('RIFE: CUDA is not available')

**Comment by aodgizmo** [comment]
You need to  run nvcc --version. It will tell you if its installed or not.

**Comment by Usulyre** [comment]
> You need to run nvcc --version. It will tell you if its installed or not.

C:\Windows\System32>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

**Comment by aodgizmo** [comment]
Great, so that is installed correctly. The error you are getting I have no experience with. So looks like my help ends here. I wish you luck!
