### ISSUE TITLE
Script evaluation failed

### ISSUE THREAD

**Issue by ac615223s5** [HolyWu/vs-rife#41]
[vapoursynth] clip = rife(clip,factor_num=2,factor_den=1,sc_threshold=0.1,trt=True)
[vapoursynth] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[vapoursynth] File "C:\Python311\Lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context
[vapoursynth] return func(*args, **kwargs)
[vapoursynth] ^^^^^^^^^^^^^^^^^^^^^
[vapoursynth] File "C:\Python311\Lib\site-packages\vsrife_init_.py", line 208, in rife
[vapoursynth] flownet = lowerer(
[vapoursynth] ^^^^^^^^
[vapoursynth] File "C:\Python311\Lib\site-packages\torch_tensorrt\fx\lower.py", line 316, in call
[vapoursynth] return do_lower(module, inputs)
[vapoursynth] ^^^^^^^^^^^^^^^^^^^^^^^^
[vapoursynth] File "C:\Python311\Lib\site-packages\torch_tensorrt\fx\passes\pass_utils.py", line 118, in pass_with_validation
[vapoursynth] processed_module = pass_(module, input, *args, **kwargs)
[vapoursynth] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[vapoursynth] File "C:\Python311\Lib\site-packages\torch_tensorrt\fx\lower.py", line 313, in do_lower
[vapoursynth] lower_result = pm(module)
[vapoursynth] ^^^^^^^^^^
[vapoursynth] File "C:\Python311\Lib\site-packages\torch\fx\passes\pass_manager.py", line 238, in call
[vapoursynth] out = _pass(out)
[vapoursynth] ^^^^^^^^^^
[vapoursynth] File "C:\Python311\Lib\site-packages\torch\fx\passes\pass_manager.py", line 238, in call
[vapoursynth] out = _pass(out)
[vapoursynth] ^^^^^^^^^^
[vapoursynth] File "C:\Python311\Lib\site-packages\torch_tensorrt\fx\passes\lower_pass_manager_builder.py", line 202, in lower_func
[vapoursynth] lowered_module = self._lower_func(
[vapoursynth] ^^^^^^^^^^^^^^^^^
[vapoursynth] File "C:\Python311\Lib\site-packages\torch_tensorrt\fx\lower.py", line 178, in lower_pass
[vapoursynth] interp_res: TRTInterpreterResult = interpreter(mod, input, module_name)
[vapoursynth] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[vapoursynth] File "C:\Python311\Lib\site-packages\torch_tensorrt\fx\lower.py", line 130, in call
[vapoursynth] interp_result: TRTInterpreterResult = interpreter.run(
[vapoursynth] ^^^^^^^^^^^^^^^^
[vapoursynth] File "C:\Python311\Lib\site-packages\torch_tensorrt\fx\fx2trt.py", line 251, in run
[vapoursynth] engine = self.builder.build_engine(self.network, builder_config)
[vapoursynth] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[vapoursynth] clip = rife(clip,factor_num=2,factor_den=1,sc_threshold=0.1,trt=True)
[vapoursynth] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[vapoursynth] File "C:\Python311\Lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context
[vapoursynth] return func(*args, **kwargs)
[vapoursynth] ^^^^^^^^^^^^^^^^^^^^^
[vapoursynth] File "C:\Python311\Lib\site-packages\vsrife_init_.py", line 227, in rife
[vapoursynth] clip = sc_detect(clip, sc_threshold)
[vapoursynth] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[vapoursynth] File "C:\Python311\Lib\site-packages\vsrife_init_.py", line 279, in sc_detect
[vapoursynth] sc_clip = clip.resize.Bicubic(format=vs.GRAY8, matrix_s="709").misc.SCDetect(threshold)
[vapoursynth] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[vapoursynth] File "src\cython\vapoursynth.pyx", line 2007, in vapoursynth.VideoNode.getattr
[vapoursynth] AttributeError: There is no attribute or namespace named misc
[vapoursynth]
[vapoursynth] could not init VS

**Comment by HolyWu** [comment]
https://github.com/HolyWu/vs-rife/blob/50781aa401196cb2ac01dcf790738e142388a4a1/README.md?plain=1#L8
