### ISSUE TITLE
how to use this as a filter?

### ISSUE THREAD

**Issue by Usulyre** [HolyWu/vs-rife#5]
Hi, any way to use this as a filter - vapoursynth?

**Comment by AIVFI** [comment]
You can use this filter to interpolate frames during real-time video playback.

NVIDIA GeForce RTX 3070 Ti allows you to double the frames without downscaling (scale=1.0) for 720p video files: https://www.svp-team.com/forum/viewtopic.php?pid=79315#p79315 

NVIDIA GeForce RTX 4090 will be over 2x more powerful than NVIDIA GeForce RTX 3090, so you can expect real-time interpolation for 1080p files.
