### ISSUE TITLE
VapourSynth-RIFE-ncnn-Vulkan (RIFE-r9-win64.7z)

### ISSUE THREAD

**Issue by NenelFX** [HolyWu/vs-rife#51]
Did you make the plugin "https://github.com/HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan" (RIFE-r9-win64.7z)?
and because I wanted to use rife-v4.8
but it gives the error "layer MemoryData not exists or registered"
I already tried using the version of "https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan"
but it doesn't work on my pc.
with RIFE.dll I can use even rife-v4.0
I would like to know if you still have the "Source code (zip)"
because "https://github.com/HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan" is no longer on github

**Comment by HolyWu** [comment]
I don't have files anymore on my machine. You should file an issue on https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/issues ranther than here if you have problems running their release.
