### ISSUE TITLE
flownet_v4.22.lite.pkl ?

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-rife#57]
For some time now https://github.com/HolyWu/vs-rife/blob/master/vsrife/__main__.py#L55 lists flownet_v4.22.lite.pkl and later tries to download https://github.com/HolyWu/vs-rife/releases/download/model/flownet_v4.22.lite.pkl but there is no such file.
Would be nice if you either could upload the file or adjust the code.
Thanks!

**Comment by HolyWu** [comment]
Uploaded, thanks.
