### ISSUE TITLE
Lastest Dependencies?

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-rife#59]
README.md states:
* [PyTorch](https://pytorch.org/get-started/) 2.5.0.dev
* [Torch-TensorRT](https://pytorch.org/TensorRT/) 2.5.0.dev
but `pip install --pre -U torch torchvision torch_tensorrt --index-url https://download.pytorch.org/whl/nightly/cu124 --extra-index-url https://pypi.nvidia.com` installs 2.6.0dev, which does break some other stuff I'm using.
=> Do you know which are the latest 2.5.X versions for torch torchvision torch_tensorrt that work, so I can avoid installing 2.6.x dev?

**Comment by HolyWu** [comment]
README updated. I'm using 2.6.0.dev and do not encounter issue.

**Comment by Selur** [comment]
Okay for me, for example, [ vs-code](https://github.com/HolyWu/vs-codeformer) with lib doesn't work anymore.
Since you have no problems, it must be something else with my system.

**Comment by HolyWu** [comment]
I was only referring to vs-rife for no issue with 2.6.0.dev. Other projects may or may not have issue.

**Comment by Selur** [comment]
Okay, like I wrote, 'which does break some other stuff I'm using' I have no direct problem with vs-rife.
