### ISSUE TITLE
[Q] 0bit models in the repo

### ISSUE THREAD

**Issue by sl1pkn07** [HolyWu/vs-rife#6]
Hi

i see in the model folders, have a files (models?) with 0bits, i presume when the plugin "learn", the models is filled with the data

this is correct?

then, in a system with install this plugin as system-wide, these models should be have a write permissions? (in case of linux)

greetings

**Comment by HolyWu** [comment]
The model files will be downloaded when you run the second step in https://github.com/HolyWu/vs-rife#installation.

**Comment by sl1pkn07** [comment]
ok, i see the download links in https://github.com/HolyWu/vs-rife/blob/master/vsrife/__main__.py

EDIT: executing the file with python download the models automagic

i need this because is for create a archlinux package, i need fetch all the sources before or durning the package creation before install

tnx and greetings
