### ISSUE TITLE
Get error when using ffmpeg

### ISSUE THREAD

**Issue by KiritoGuugk** [HolyWu/vs-rife#67]
when using ffmpeg to convert a video: `vspipe -c y4m --arg in_filename="xxx.mkv"   /home/xxx/Documents/rife.vpy - | ffmpeg -f yuv4mpegpipe -i - output.mkv` or using ffplay to play I get error: `[yuv4mpegpipe @ 0x55f529804ac0] Invalid magic number for yuv4mpeg.
`
while mpv can play video correctly.
My OS is archlinux and before I updated the whole system(and vs-rife) it worked well in ffmpeg and mpv, but now it only works in mpv.   

rife.vpy:
```import vapoursynth as vs
from vsrife import rife

core = vs.core
clip = core.ffms2.Source(source=in_filename)
clip = core.resize.Lanczos(clip=clip, format=vs.RGBH, matrix_in_s="709")
clip = rife(
    clip=clip,
    model="4.6",
    factor_num=3, 
    factor_den=1,
    device_index=0,
    scale=1,
    sc=True,
    trt=True,
    trt_optimization_level=3
)
clip = core.resize.Lanczos(clip, format=vs.YUV420P8, matrix_s="2020ncl")

clip.set_output()
```

**Comment by HolyWu** [comment]
It seems a warning from TensorRT was sent to `stdout` rather than `stderr`, causing corrupted pipe. Please modify `tensorrt_bindings/plugin/__init__.py` in your Python site-packages and remove this line:
```py
logger.log(trt.Logger.WARNING, f"Functionality provided through tensorrt.plugin module is experimental.")
```

**Comment by KiritoGuugk** [comment]
> It seems a warning from TensorRT was sent to `stdout` rather than `stderr`, causing corrupted pipe. Please modify `tensorrt_bindings/plugin/__init__.py` in your Python site-packages and remove this line:
> 
> ```python
> logger.log(trt.Logger.WARNING, f"Functionality provided through tensorrt.plugin module is experimental.")
> ```

Thank you very much for your reminder. Everything is working well now. I am not very familiar with the use of Linux pipes. This is not an issue with this repository. Apologies for the inconvenience.
