### ISSUE TITLE
New RIFE_m model

### ISSUE THREAD

**Issue by oblessnoob** [HolyWu/vs-rife#8]
https://github.com/hzwer/arXiv2020-RIFE/blob/main/model/IFNet_m.py

https://drive.google.com/file/d/147XVsDXBfJPlyct2jfo9kpbL944mNeZr/view?usp=sharing

**Comment by AIVFI** [comment]
Finally we have a new RIFE_m_ for arbitrary-timestep frame interpolation.
The progress is enormous. Finally the interpolation results for DAIN and EDSCm have been beaten:

old results: https://arxiv.org/pdf/2011.06294v6.pdf
new results: https://arxiv.org/pdf/2011.06294.pdf

HolyWu, please add **RIFE_m_** and **4x interpolation** to vs-rife.
